---

- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 16.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    name: nodejs
    state: present

- name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - firebase-tools